export default function LovablePage() {
  return (
    <div className="min-h-screen bg-neutral-950">
      <main className="mx-auto max-w-3xl px-6 pt-32 pb-24">
        <h1 className="text-3xl font-bold tracking-tight text-white">
          Lovable Integration
        </h1>
        <p className="mt-3 text-neutral-400">
          Configure Lovable to generate code using n3wth/kit components.
        </p>

        <section className="mt-12">
          <h2 className="text-lg font-semibold text-white">
            1. Reference registry URLs in prompts
          </h2>
          <p className="mt-3 text-sm text-neutral-400">
            Lovable supports the shadcn registry protocol. Include the n3wth/kit
            registry URL when prompting Lovable to generate UI.
          </p>
          <pre className="mt-4 overflow-x-auto rounded-lg border border-neutral-800 bg-neutral-900 p-4 font-mono text-sm text-neutral-300">{`Use components from the n3wth/kit registry:
https://kit.newth.ai/r/

Build a landing page with hero, card grid, and footer.`}</pre>
        </section>

        <section className="mt-12">
          <h2 className="text-lg font-semibold text-white">
            2. Provide component context
          </h2>
          <p className="mt-3 text-sm text-neutral-400">
            For best results, include the component metadata URL so Lovable
            understands the full API surface of each component.
          </p>
          <pre className="mt-4 overflow-x-auto rounded-lg border border-neutral-800 bg-neutral-900 p-4 font-mono text-sm text-neutral-300">
            https://kit.newth.ai/ai/components.json
          </pre>
          <p className="mt-3 text-sm text-neutral-400">
            This JSON file contains props, usage examples, and accessibility
            notes for every component in the registry.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-lg font-semibold text-white">
            3. Install components locally
          </h2>
          <p className="mt-3 text-sm text-neutral-400">
            After exporting your Lovable project, install the n3wth/kit
            components it used.
          </p>
          <pre className="mt-4 overflow-x-auto rounded-lg border border-neutral-800 bg-neutral-900 p-4 font-mono text-sm text-neutral-300">{`npx shadcn add https://kit.newth.ai/r/hero.json
npx shadcn add https://kit.newth.ai/r/card.json
npx shadcn add https://kit.newth.ai/r/footer.json`}</pre>
        </section>

        <section className="mt-12">
          <h2 className="text-lg font-semibold text-white">
            Design system consistency
          </h2>
          <p className="mt-3 text-sm text-neutral-400">
            n3wth/kit components use CSS custom properties for theming. Once
            installed, all components share the same design tokens, ensuring
            visual consistency whether generated by Lovable or written by hand.
          </p>
          <p className="mt-3 text-sm text-neutral-400">
            See the{' '}
            <a
              href="/docs/getting-started"
              className="text-white underline underline-offset-4"
            >
              getting started guide
            </a>{' '}
            for the full setup.
          </p>
        </section>
      </main>
    </div>
  )
}
